server:
  port: 8081


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.43.9.197:3306/questions?characterEncoding=utf8&useUnicode=true&useSSL=true
    username: questions
    password: lzq@@951201

logging:
  config: classpath:logback-lab-dev.xml
  file:
    path: D:/logs/springBoot
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss}] -- [%-5p]: [%c] -- %m%n'
    file: '[%d{yyyy-MM-dd HH:mm:ss}] -- [%-5p]: [%c] -- %m%n'


aio:
  knife4j:
    title: Lab在线接口文档 - 0.1.0
    group: ''
    description: Lab 在线接口文档
    version: 1.0
    contact:
      name: aio
      url: 'http://api.kidoneself.com:8081/doc.html#/home'
      email: 'kiddoneself@gmail.com '

#打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload:
    path: /Users/lizhiqiang/IdeaProjects/app/
    allowTypes: 'jpeg'
